language: cpp
compiler:
  - gcc
dist: trusty
sudo: required

script: 
    - cd  ${TRAVIS_BUILD_DIR}/test
    - rm ./tls/dh1024.pem
    - openssl dhparam -out ./tls/dh1024.pem 1024
    - cat package.json
    - npm install
    - npm test
    - cat /tmp/drachtio.log

git:
    submodules: false

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install gcc g++ build-essential make git autoconf curl libz-dev ncurses-dev libpcap-dev
    - sudo chmod 0777 /usr/local/src 
    - cd /usr/local/src
    - git clone https://github.com/SIPp/sipp.git && cd sipp && git checkout v3.5.1 
    - ./build.sh  --with-rtpstream --with-pcap 
    - sudo make install
    - sudo apt-get install -y libcurl4-openssl-dev
    - sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install -y nodejs
    - curl-config --version
    - curl-config --libs 
    - cd $TRAVIS_BUILD_DIR
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - ./bootstrap.sh
    - mkdir build && cd build
    - ../configure
    - make
    - ./drachtio --version 
    - node --version
    - sudo npm install -g npm
