language: cpp
sudo: required

matrix:
  include:
    - os: osx

    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - libtool-bin

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - libtool-bin

    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - libtool-bin
    
script: 
    - cd  ${TRAVIS_BUILD_DIR}/test
    - rm ./tls/dh1024.pem
    - openssl dhparam -out ./tls/dh1024.pem 1024
    - cat package.json
    - npm install
    - if [ $TRAVIS_OS_NAME = linux ]; then npm test; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then cat /tmp/drachtio.log; fi

git:
    submodules: false

before_install:
    - eval "${MATRIX_EVAL}"
    - if [ $TRAVIS_OS_NAME = osx ]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi
    - if [ $TRAVIS_OS_NAME = osx ]; then nvm install "v8.11.3"; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y curl libz-dev ncurses-dev libpcap-dev libtool libcurl4-openssl-dev nodejs; else brew install curl ncurses libpcap libtool openssl gnu-sed; fi 
    - if [ $TRAVIS_OS_NAME = osx ]; then sudo ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
    - sudo mkdir -p /usr/local/src && sudo chmod 0777 /usr/local/src 
    - cd /usr/local/src
    - git clone https://github.com/SIPp/sipp.git && cd sipp && git checkout v3.5.1 
    - ./build.sh  --with-rtpstream --with-pcap 
    - sudo make install
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - ; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y nodejs; fi
    - curl-config --version
    - curl-config --libs 
    - cd $TRAVIS_BUILD_DIR
    - if [ $TRAVIS_OS_NAME = linux ]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; else gsed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
    - git submodule update --init --recursive
    - ./autogen.sh
    - mkdir build && cd build
    - ../configure
    - make
    - ./drachtio --version 
    - node --version
    - npm --version
    - openssl version
    - which openssl
