name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          libboost-filesystem-dev
          libboost-log-dev
          libboost-system-dev
          libboost-thread-dev
          libcurl4-openssl-dev
          libgoogle-perftools-dev
          libpcap-dev
          libtool
          libtool-bin
          libunwind-dev
      - name: build sipp
        run: |
          sudo chmod a+w /usr/local/src/
          cd /usr/local/src/
          git clone https://github.com/SIPp/sipp.git -b v3.6.1 --depth 20
          cd sipp
          ./build.sh --common
          sudo make install
      - name: build drachtio
        run: |
          ./autogen.sh
          mkdir -p build && cd $_
          ../configure --enable-tcmalloc=yes
          make
          sudo make install
      - name: install nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: run ci tests
        run: |
          cd test
          npm install 
          npm run test-ci
          cat /tmp/drachtio.log
